services:
  postgres:
    image: postgres:16.9-alpine3.22
    environment:
      POSTGRES_DB: basic_http
      POSTGRES_USER: basic_http
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U basic_http -d basic_http"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - app-network
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_DSN: "postgres://basic_http:password@postgres:5432/basic_http?sslmode=disable"
      ENVIRONMENT: "PRODUCTION"
    networks:
      - app-network


  frontend:
    build:
      context: .
      dockerfile: client.Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
    driver: bridge